#!/usr/bin/env python3
"""Write reports/coverage.md: how much of the roster and the belief-system list has records, and how full they are.

Usage:
    python scripts/coverage_report.py            # write reports/coverage.md
    python scripts/coverage_report.py --stdout   # print instead of writing
    python scripts/coverage_report.py --check    # exit 1 if reports/coverage.md is out of date

The report is derived only from files in the repo, so it can be regenerated at any time.
It has no timestamp, which keeps the file stable when nothing has changed.
"""
import argparse, collections, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.records import REPO, read_record, read_csv, person_files, system_files, fill_counts, claims, claim_state  # noqa: E402

FIRST_POOL = ["faraday-michael", "maxwell-james-clerk", "newton-isaac", "aquinas-thomas", "ibn-sina", "godel-kurt"]
BAND_ORDER = ["high (5)", "core (3–4)", "extended (2)", "single-source (1)"]
STATUS_ORDER = ["stub", "example — unreviewed", "draft — unreviewed", "in review", "reviewed", "needs revision"]
STATES = ["FILLED", "TODO", "UNKNOWN", "BELOW_THRESHOLD"]


def pct(a, b):
    return f"{100 * a / b:.1f}%" if b else "–"


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out


def fill_table(totals):
    rows = []
    for sec, c in totals.items():
        n = sum(c.values())
        rows.append([sec, n, c["FILLED"], c["TODO"], c["UNKNOWN"], c["BELOW_THRESHOLD"], pct(c["FILLED"], n)])
    allc = {s: sum(c[s] for c in totals.values()) for s in STATES}
    n = sum(allc.values())
    rows.append(["**all**", n, allc["FILLED"], allc["TODO"], allc["UNKNOWN"], allc["BELOW_THRESHOLD"], pct(allc["FILLED"], n)])
    return table(["section", "claims", "filled", "TODO", "UNKNOWN", "BELOW_THRESHOLD", "filled %"], rows)


def build():
    roster = read_csv(os.path.join(REPO, "data", "roster", "roster.csv"))
    ids = read_csv(os.path.join(REPO, "data", "roster", "person_ids.csv"))
    name_to_id = {r["canonical_name"]: r["id"] for r in ids}
    by_id = {r["canonical_name"]: r for r in roster}

    people = {}
    problems = []
    for path in person_files():
        try:
            data, _ = read_record(path)
        except Exception as e:  # report, don't crash
            problems.append(f"{os.path.relpath(path, REPO)}: {e}")
            continue
        people[os.path.basename(path)[:-3]] = data

    L = ["# Coverage report", "",
         "Generated by `scripts/coverage_report.py` from the files in this repo. Do not edit by hand; rerun the script.", ""]

    # ---- people
    n_roster = len(roster)
    L += ["## People", "",
          f"Person files: **{len(people)}** of **{n_roster}** roster entries ({pct(len(people), n_roster)}).", ""]
    if problems:
        L += ["Files that could not be read:", ""] + [f"- {p}" for p in problems] + [""]

    have = {r["canonical_name"] for r in roster if name_to_id.get(r["canonical_name"]) in people}
    L += ["### By frequency band (F = number of the five model lists naming the person)", ""]
    rows = []
    for b in BAND_ORDER:
        names = [r["canonical_name"] for r in roster if r["band"] == b]
        k = sum(1 for n in names if n in have)
        rows.append([b, len(names), k, pct(k, len(names))])
    L += table(["band", "roster", "files", "coverage"], rows) + [""]

    L += ["### By field bucket", ""]
    rows = []
    for fb in sorted({r["field_bucket"] for r in roster}):
        names = [r["canonical_name"] for r in roster if r["field_bucket"] == fb]
        k = sum(1 for n in names if n in have)
        rows.append([fb, len(names), k, pct(k, len(names))])
    L += table(["field bucket", "roster", "files", "coverage"], rows) + [""]

    L += ["### Review status of person files", ""]
    sc = collections.Counter((d.get("record") or {}).get("review_status", "(missing)") for d in people.values())
    L += table(["review status", "files"], [[s, sc.get(s, 0)] for s in STATUS_ORDER] +
               [[s, c] for s, c in sc.items() if s not in STATUS_ORDER]) + [""]

    L += ["### Claim fill rates, all person files, by section", "",
          "A claim is any field that takes the claim shape (value + certainty + cites). "
          "TODO = not yet researched; UNKNOWN = researched, not findable; BELOW_THRESHOLD = evidence below the 0.5 certainty floor.", ""]
    totals = collections.OrderedDict()
    for d in people.values():
        for sec, c in fill_counts(d).items():
            t = totals.setdefault(sec, dict.fromkeys(STATES, 0))
            for s in STATES:
                t[s] += c[s]
    L += (fill_table(totals) if totals else ["(no person files yet)"]) + [""]

    L += ["### Worldview coding status", ""]
    wv_rows = []
    for pid, d in sorted(people.items()):
        wv = d.get("worldview") or {}
        prim = (wv.get("primary_system") or {}).get("value", "(missing)")
        wv_rows.append([pid, prim, (d.get("record") or {}).get("review_status", "")])
    L += (table(["id", "primary system", "review status"], wv_rows) if wv_rows else ["(none)"]) + [""]

    L += ["### First pool checklist", "",
          "The v7.1 coding rules name a first pool of people to code before anyone else.", ""]
    rows = []
    idrow = {r["id"]: r for r in ids}
    for pid in FIRST_POOL:
        r = idrow.get(pid)
        name = r["canonical_name"] if r else "(id not in person_ids.csv)"
        ro = by_id.get(name, {})
        d = people.get(pid)
        rows.append([name, f"`{pid}`", ro.get("F", "?"), "yes" if d else "no",
                     (d.get("record") or {}).get("review_status", "") if d else ""])
    L += table(["person", "id", "F", "file", "review status"], rows) + [""]

    # ---- systems
    systems = {}
    for path in system_files():
        try:
            systems[os.path.basename(path)[:-3]], _ = read_record(path)
        except Exception as e:
            problems.append(f"{os.path.relpath(path, REPO)}: {e}")
    L += ["## Belief systems", "",
          f"System files: **{len(systems)}** (the v7.1 data book lists 77).", ""]
    sc = collections.Counter((d.get("record") or {}).get("review_status", "(missing)") for d in systems.values())
    L += table(["review status", "files"], [[s, sc.get(s, 0)] for s in STATUS_ORDER] +
               [[s, c] for s, c in sc.items() if s not in STATUS_ORDER]) + [""]
    lab = collections.Counter((d.get("identity") or {}).get("label_status", "(missing)") for d in systems.values())
    L += ["Display label status:", ""] + table(["label status", "files"], sorted(lab.items())) + [""]

    L += ["### Claim fill rates, all system files, by section", ""]
    totals = collections.OrderedDict()
    for d in systems.values():
        for sec, c in fill_counts(d).items():
            t = totals.setdefault(sec, dict.fromkeys(STATES, 0))
            for s in STATES:
                t[s] += c[s]
    L += (fill_table(totals) if totals else ["(no system files)"]) + [""]

    L += ["### Systems that are past stub stage", ""]
    rows = []
    for code, d in sorted(systems.items()):
        st = (d.get("record") or {}).get("review_status")
        if st != "stub":
            f = sum(1 for _, c in claims(d) if claim_state(c) == "FILLED")
            n = sum(1 for _ in claims(d))
            rows.append([code, (d.get("identity") or {}).get("display_label", ""), st, f"{f}/{n}",
                         (d.get("revised_rubric") or {}).get("status", "")])
    L += (table(["code", "display label", "review status", "claims filled", "revised rubric"], rows) if rows else ["(none)"]) + [""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = build()
    out = os.path.join(REPO, "reports", "coverage.md")
    if a.stdout:
        print(text)
    elif a.check:
        cur = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if cur != text:
            print("reports/coverage.md is out of date; run scripts/coverage_report.py")
            sys.exit(1)
        print("reports/coverage.md up to date")
    else:
        os.makedirs(os.path.dirname(out), exist_ok=True)
        open(out, "w", encoding="utf-8").write(text)
        print(f"wrote {os.path.relpath(out, REPO)}")


if __name__ == "__main__":
    main()
