#!/usr/bin/env python3
"""Write the progress status table in README.md from the repo's own files.

Usage:
    python scripts/progress_status.py            # rewrite the table in README.md
    python scripts/progress_status.py --stdout   # print the table instead
    python scripts/progress_status.py --check    # exit 1 if the README table is out of date

The table sits between the markers <!-- BEGIN GENERATED: progress --> and
<!-- END GENERATED: progress --> in README.md. Everything outside the markers is hand-written.

Where each row comes from:
    roster counts      data/roster/roster.csv (status column)
    people coded       person files in people/ whose roster status is core
    systems sourced    systems/*.md whose review_status is not "stub"
    decisions          the summary table in docs/OPEN_DECISIONS.md (rows marked "decided")
    latest tag         `git tag --sort=-creatordate` (falls back to "none" outside a git checkout)
    audits, next steps MANUAL: the AUDITS and NEXT_STEPS constants below. Update them by hand.
"""
import argparse, collections, os, re, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.records import REPO, read_record, read_csv, person_files, system_files  # noqa: E402

README = os.path.join(REPO, "README.md")
BEGIN, END = "<!-- BEGIN GENERATED: progress -->", "<!-- END GENERATED: progress -->"

# MANUAL rows. No file in the repo records these as data, so they are kept here by hand.
AUDITS = ("3 blind lens runs on one 115-claim packet (commit eff4700); see "
          "[reports/audit_2026-10-02.md](reports/audit_2026-10-02.md)")
NEXT_STEPS = "Code more core people; fill the system stubs; the revised rubric has not started"


def latest_tag():
    try:
        out = subprocess.run(["git", "-C", REPO, "tag", "--sort=-creatordate"], capture_output=True, text=True, check=True)
        tags = [t for t in out.stdout.split() if t]
        return f"`{tags[0]}`" if tags else "none"
    except (OSError, subprocess.CalledProcessError):
        return "none"


def decisions():
    rows = re.findall(r"^\| ([RPS]\d+) \|.*\|\s*([^|]*?)\s*\|\s*$",
                      open(os.path.join(REPO, "docs", "OPEN_DECISIONS.md"), encoding="utf-8").read(), re.M)
    ids = {}
    for i, status in rows:
        ids.setdefault(i, status)
    settled = sum(1 for s in ids.values() if s.startswith("decided"))
    return settled, len(ids)


def table():
    roster = read_csv(os.path.join(REPO, "data", "roster", "roster.csv"))
    st = collections.Counter(r["status"] for r in roster)
    core_names = {r["canonical_name"] for r in roster if r["status"] == "core"}
    coded = 0
    for f in person_files():
        d, _ = read_record(f)
        if d["identity"]["roster"]["canonical_name"] in core_names:
            coded += 1
    systems = [read_record(f)[0] for f in system_files()]
    sourced = sum(1 for d in systems if d["record"]["review_status"] != "stub")
    settled, n_dec = decisions()
    tag = latest_tag()
    other = len(roster) - st["core"] - st["provisional"] - st["review"]
    rows = [
        ("Roster people", f"{len(roster):,}: {st['core']} core, {st['provisional']} provisional, {st['review']} review"
                          + (f", {other} new names still need a status" if other else "")),
        ("People coded (of core)", f"{coded} / {st['core']} (draft, unreviewed)"),
        ("Belief systems sourced", f"{sourced} / {len(systems)} (the rest are stubs)"),
        ("Decisions settled", f"{settled} / {n_dec}"),
        ("Audits", AUDITS),
        ("Latest tag", tag + (" (prerelease)" if re.search(r"alpha|beta|rc", tag) else "")),
        ("Next steps", NEXT_STEPS),
    ]
    out = [BEGIN,
           "<!-- Generated by scripts/progress_status.py; the Audits and Next steps rows are manual constants in that script. -->",
           "", "| Item | Status |", "|---|---|"]
    out += [f"| {k} | {v} |" for k, v in rows]
    out += ["", END]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    new = table()
    if a.stdout:
        print(new)
        return
    text = open(README, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        sys.exit(f"README.md has no {BEGIN} ... {END} block")
    i, j = text.index(BEGIN), text.index(END) + len(END)
    updated = text[:i] + new + text[j:]
    if a.check:
        if updated != text:
            print("README.md progress table is out of date; run scripts/progress_status.py")
            sys.exit(1)
        print("README.md progress table up to date")
        return
    if updated != text:
        open(README, "w", encoding="utf-8").write(updated)
        print("updated README.md progress table")
    else:
        print("README.md progress table already up to date")


if __name__ == "__main__":
    main()
